### ISSUE TITLE
Tint Sprite to match Color

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#14]
The generate sprites don't have a tint matching the color stat. For example [this Indigo Wool Hat](https://kazetsukai.github.io/onetech/#742/Indigo-Wool-Hat) isn't blue.

**Comment by Kazetsukai** [comment]
I took a first cut at tinting, but messed something up. I was expecting the hot coals to be tinted red, and they definitely weren't (they were still white). I believe I got as far as confirming that they were set to white in the sprite information, and my guess was that their colour is based off an animation rather than a static tint. Also didn't see any change in the skin tones object with first experiment, so I put it down at that point.

With the dyeable items, which DO seem to use the color tint specified (i.e. https://github.com/jasonrohrer/OneLifeData7/blob/5c2b04f78a02d6a52700141c56f3ad9620e338b3/objects/725.txt#L33), might be worth reviving this.

**Comment by Kazetsukai** [comment]
Looks like the hot coals do in fact use that color tint as well, I am beginning to think it was a tired brain leading to a bug in the tint code I was writing. https://github.com/jasonrohrer/OneLifeData7/blob/f01e9e42406677ed476c7344c7329cf1da79a69b/objects/85.txt#L78
