### ISSUE TITLE
Support opening up separate tabs

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#21]
There's no easy way to open an object in a separate tab. Right clicking an object does not give an option, and holding the command key (on a Mac) does not open up a separate tab like a normal link would.

To resolve this, we could replace the Click + Event Bus system with links that go to the hash.

**Comment by Kazetsukai** [comment]
Yep, good spotting. Now that we have URL routing we can pull out the event bus entirely I believe.

**Comment by ryanb** [comment]
I'm using the event bus to expand the tech tree which doesn't change the URL, so we'll need to keep it for that.

**Comment by Kazetsukai** [comment]
Here where you call a method that publishes an event on the TechTreeNode that is picked up by TechTree, you could possibly make that `onExpandTree(object)` and have onExpandTree be a property that is passed in. 

https://github.com/Kazetsukai/onetech/blob/master/src/components/TechTreeNode.vue#L17

Would feel a little odd since it is a recursive component, but that would just mean passing the onExpandTree method down to child nodes as well. That would keep it all wrapped up a bit more nicely, and decouple the last bit preventing us from using anchor tags for links.

I might try and do this refactor at lunchtime today.

**Comment by Kazetsukai** [comment]
https://github.com/Kazetsukai/onetech/commit/f6b125bbe60fca8e91b733da534a69e586b852df fixes this, I will process and build when I am at my mac tomorrow.

**Comment by ryanb** [comment]
That looks awesome. I like the simplicity of removing the event bus.
