### ISSUE TITLE
Downloading the data .tar does not handle deleted items

### ISSUE THREAD

**Issue by UncleGus** [Kazetsukai/onetech#37]
It overwrites, but does not delete, so you can still end up with ghost objects and transitions that have been deleted from the data repository.

**Comment by Kazetsukai** [comment]
Good spotting

**Comment by ryanb** [comment]
@UncleGus the process script now uses the Git repo instead of downloading the tar. Also you can customize the git repo through an environment variable.

```
export ONETECH_PROCESS_GIT_URL="https://..."
```

This means you don't need to edit the process script to change the Git repo.

An unrelated note, the version is tracked in an object. This is done using tags on the `OneLifeData7` repo. If you use your own tags for your forked version you might need to update the `VersionPopulator` class to support it. You can make an issue about this if you need help.
