### ISSUE TITLE
Filter objects by type

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#39]
What about ways to filter objects by their type?
* Food
* Clothing
* Tools
* Containers
* Animals
* Natural

Any others?

**Comment by Kazetsukai** [comment]
This feels like an easyish feature with big benefit.

**Comment by ryanb** [comment]
I've been thinking about how to present filters. How about this?

<img width="1050" alt="screen shot 2018-04-06 at 1 14 22 pm" src="https://user-images.githubusercontent.com/161/38442253-90c8776a-399c-11e8-902d-9a065b450604.png">

The starting page can be these categories, clicking "Latest Additions" would show all of the items sorted by their version.

**Comment by Kazetsukai** [comment]
Feels very strange to me, because it uses the same design as items. If they are differentiated somehow visually i.e. with a thick border or a tinted background color it should look better, and you will know subconsciously that clicking on it won't take you to an item details page.

Next thought: Should we have images on them? Not sure how to select a good image given that
- Jason will be updating the game and it will eventually become much higher tech level
- Want to maintain support for custom modded servers like the one @UncleGus is doing
Maybe pick latest/most complex from a category could work? Or even 4 or 5 from each laid out in a row/circle? Text only at first makes that easier and also separates them visually from item buttons. Maybe even something like fontawesome icons?
