### ISSUE TITLE
Deep Well has no "refilling" transition

### ISSUE THREAD

**Issue by jaloveast1k** [Kazetsukai/onetech#45]
https://kazetsukai.github.io/onetech/#663/Deep-Well
Lets take a look. Deep Well refills one charge every 5 minutes. There is transition that I believe is responsible for this behaviour - "-1_663.txt", but your parser have not parsed it for some reason.
Even tho it successfully parsed "-1_30.txt" - wild berry bush regrowing one berry every ten minutes, which looks the same to me.

**Comment by Kazetsukai** [comment]
Good spotting. We currently don't have "reverse one use" style transitions implemented and parsed. We hide transitions that come from and go to the same object. What you are seeing on the berry bush is a specific transition `-1_279_LT.txt` which goes from empty berry bush to berry bush. There is no transition from dry well to well, which is why that doesn't show up.

**Comment by ryanb** [comment]
Thanks for reporting. Seems I went to far attempting to remove the junk transitions.

**Comment by Kazetsukai** [comment]
I'm not sure adding them straight back in is the right answer. Or rather, I want a large "+1" on the target in any "reverseUseTarget" transitions, so it is more obvious that what is happening is one "use" being recharged.

**Comment by ryanb** [comment]
Alright, I'll reopen this to make those transitions clearer.

**Comment by Kazetsukai** [comment]
https://github.com/Kazetsukai/onetech/issues/46

**Comment by ryanb** [comment]
Haha, closing this again since we have issue #46 now.
