### ISSUE TITLE
Recipe cards are confusing

### ISSUE THREAD

**Issue by Kazetsukai** [Kazetsukai/onetech#6]
The 4 corner layout I made for the recipe cards is confusing. Would be better to lay out the recipes as rows, with 4 squares going across, ideally center justified as so:

    #+# > # #
      # > # #
    #+# > #

**Comment by ryanb** [comment]
This would make the page wider if we keep the same layout. Instead of a 3 column layout, should it be 2 column with the object info on one side and transitions on the other? The to/from transitions can be stacked with a title, perhaps collapsable/expandable.

This would also help the mobile design because at the moment transitions are displayed together with no title to distinguish them.

**Comment by Kazetsukai** [comment]
I like the title idea, just having a think about what would make sense.
Some kind of wording change on:
- How to get
- How to use
perhaps?

**Comment by ryanb** [comment]
How to get/use sounds alright to me. I like the word "craft" or "make" better than "get" but it doesn't apply to everything.

Regarding the refill transitions where `targetRemains`, should that go in "How to get"?

**Comment by Kazetsukai** [comment]
Yeah, could even be a third category for timed transitions, but for now "How to get" is probably the best place.
